[package]
name = "prady-parser"
version = "0.1.0"
edition = "2021"
authors = ["Prady Team"]
description = "Recursive-descent & Pratt parser for the Prady language"

[dependencies]
prady-diagnostics = { path = "../prady-diagnostics" }
prady-ast = { path = "../prady-ast" }
prady-lexer = { path = "../prady-lexer" }
