[workspace]
resolver = "2"
members = [
    "compiler/prady-diagnostics",
    "compiler/prady-ast",
    "compiler/prady-lexer",
    "compiler/prady-parser",
    "compiler/prady-interp",
    "compiler/prady-cli",
    "compiler/prady-lsp",
]

[workspace.package]
version = "1.0.0"
edition = "2021"
authors = ["Prady Team"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/technopradyumn/prady"
description = "The Prady Programming Language"
